services:
  - type: web
    name: mapid-academy
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn engine:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
